on:
    push:
        branches:
            - main

jobs:
    start:
     runs-on: ubuntu-latest 

     steps:
     - uses: actions/checkout@v2

     - name: executing remote ssh commands using ssh key
       uses: appleboy/ssh-action@master
       with:
       aws-access-key-id:  AKIA57GIYUHLAJVX3X2S
       aws-secret-access-key:  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
       aws-region: eu-north-1
       instance-ids: i-06c081bd7e0e243c1
          comment: Deploy the master branch
          command: /bin/sh ./deploy.sh