name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

          ls -l 
          echo "))))))))))))))))))))))))))))))))))))"
          pwd
          echo "))))))))))))))))))))))))))))))))))))"
          # Copy files to EC2 instance
          ${{secrets.PRIVATE_KEY}}  >> private.pem
          scp -o StrictHostKeyChecking=no -i private.pem ./* ubuntu@16.171.61.147:/home/ubuntu/react-deploy-ec2/
          # SSH into EC2 instance and restart the application
