name: Deploying

on:
  push:
    branches:
      - main

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1 # Replace with your desired AWS region

      - name: Execute commands on EC2 instance
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy the main branch" \
            --instance-ids ${{ secrets.INSTANCE_ID }} \
            --parameters commands="/bin/sh ./deploy.sh"
