name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Deploy to EC2
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region eu-north-1

          aws ec2 describe-instances --instance-ids ${{ secrets.INSTANCE_ID }} --query "Reservations[0].Instances[0].PublicIpAddress" --output text > ip.txt
          scp -i react-example-instance.pem -r ./build ec2-user@$(cat ip.txt):/home/ec2-user/

      - name: Restart server
        run: pm2 restart example